keyboard(
    name='flutterby',
    fqbn='adafruit:avr:feather32u4',
    vid='0xFEED',
    pid='0x6006',
    product='flutterby',
    manufacturer='Wez Furlong',
    libs=[
	"https://github.com/keyboardio/Kaleidoscope",
	"https://github.com/keyboardio/Kaleidoscope-DualUse",
	"https://github.com/keyboardio/Kaleidoscope-EEPROM-Settings",
	"https://github.com/keyboardio/Kaleidoscope-Focus",
	"https://github.com/keyboardio/Kaleidoscope-HostOS",
	"https://github.com/keyboardio/Kaleidoscope-Macros",
	"https://github.com/keyboardio/Kaleidoscope-MouseKeys",
	"https://github.com/keyboardio/Kaleidoscope-OneShot",
	"https://github.com/keyboardio/Kaleidoscope-Ranges",
	"https://github.com/keyboardio/KeyboardioHID",
        "https://github.com/keyboardio/FingerprintUSBHost",
    ]
)
